name: Maillot Jaune
description: Votez pour la personne qui a illuminé votre soirée
full_description: 'A more complete description of the mobile app<br>
<br>With a lot of features:
<br>- Feature 1
<br>- Feature 2
<br>- Feature 3'
android: https://play.google.com/store/apps/details?id=com.policy.maillot.jaune
iOS: https://testflight.apple.com/join/MMqFaksC
web: false
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
  - 5.png
