name: Maillot Jaune
description: Votez pour la personne qui a illuminé votre soirée
full_description: 'Votez pour la personne qui a illuminé votre soirée, votre match ou rendu vos vacances inoubliables.<br> 
Que ce soit pour le plus drôle, le plus festif, ou le plus mémorable, Maillot Jaune célèbre l'éclat des moments partagés.<br> 
Facile à utiliser, amusant à partager - téléchargez dès maintenant et créez des souvenirs inoubliables avec Maillot Jaune ! 🌟'
android: https://play.google.com/store/apps/details?id=com.policy.maillot.jaune
iOS: https://telegra.ph/Replace-this-link-07-23
web: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
  - 5.png
producthunt: https://telegra.ph/Replace-this-link-07-23
companies:
  - url: https://telegra.ph/Replace-this-link-07-23
    image: androidpolice.png
  - url: https://telegra.ph/Replace-this-link-07-23
    image: producthunt.png
