name: Maillot Jaune
description: Votez pour la personne qui a illuminé votre soirée
full_description: 'Votez pour la personne qui a illuminé votre soirée, votre match ou rendu vos vacances inoubliables.<br> Que ce soit pour le plus drôle, le plus festif, ou le plus mémorable, Maillot Jaune célèbre l éclat des moments partagés.<br>Facile à utiliser, amusant à partager - téléchargez dès maintenant et créez des souvenirs inoubliables avec Maillot Jaune ! <br> 
<br>With a lot of features:
<br>- Feature 1
<br>- Feature 2
<br>- Feature 3'
android: https://play.google.com/store/apps/details?id=com.policy.maillot.jaune
iOS: https://testflight.apple.com/join/MMqFaksC
web: false
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
  - 5.png
